Emails:
  Email_CC : 'mefranklin@csuchico.edu.edu'
  Email_From : 'automation@csuchico.edu'
  From_Name : 'CTS Deep Freeze Bot'
  Support_Email : 'helpdesk@example.com'
  Support_Name : 'Your Help Desk'
  SMTP_Server : 'smtp.csuchico.edu'
  SMTP_User : ''
  SMTP_Password : '' 

Utils:
  Log_Directory : 'C:\Temp'
  Encryped_PW_Location : '.\DeepFreezePassword.txt'
  
