Emails:
  Email_CC : 'youremail@example.com'
  Email_From : 'automated_email@example.com'
  From_Name : 'Help Desk Robot'
  Support_Email : 'helpdesk@example.com'
  Support_Name : 'Your Help Desk'
  SMTP_Server : 'smtp.yourorg.com'
  SMTP_User : ''

Utils:
  Log_Directory : 'C:\Temp'
  Encryped_PW_Location : '.\DeepFreezePassword.txt'
  
